const tintColorLight = "#0a7ea4";
const tintColorDark = "#00FFFF"; // anpassad till din accentfärg

export const Colors = {
  light: {
    text: "#11181C",
    background: "#fff",
    tint: tintColorLight,
    icon: "#687076",
    tabIconDefault: "#687076",
    tabIconSelected: tintColorLight,
    primary: "#00FFFF",
    secondary: "#122033",
    border: "#013255",
    borderLight: "#008FB3",
    progressBar: "#0269B0",
    textLight: "#ccc",
    textWhite: "#fff",
    checkmark: "#C3FF00",
    buttonGlow: "#00ffffcc",
    buttonTextGlow: "#00ffff88",
  },
  dark: {
    text: "#ECEDEE",
    background: "#001326",
    tint: tintColorDark,
    icon: "#00FFFF",
    tabIconDefault: "#9BA1A6",
    tabIconSelected: tintColorDark,
    primary: "#32D1A6",
    secondary: "#122033",
    border: "#013255",
    borderLight: "#008FB3",
    progressBar: "#0269B0",
    textLight: "#ccc",
    textWhite: "#fff",
    checkmarkMeal: "#00FFC8",
    checkmarkSupplement: "#C3FF00",
    buttonGlow: "#00ffffcc",
    buttonTextGlow: "#00ffff88",
    assistantBubble: "#2C2C2C",
    delete: "#FF3B30",
    error: "#FF3B30",
  },
};
